### ISSUE TITLE
Account lost ability to check discovery after migration

### ISSUE THREAD

**Issue by MilanBabuljak** [bluesky-social/pds#101]
Hello, recently I've migrated one account to my self-hosted PDS. For that, I've used the script you've provided in documentation. Everything moved correctly, but the account lost the ability to see discovery feed. Following feed works as usual. The error message provided is 500 Interial server Error

<img width="670" alt="image" src="https://github.com/user-attachments/assets/56cc9bf9-7334-489d-b681-2aa9cfa1368f">

I checked the devtools and I found this:

```
{
    "error": "checking jwt failed: failed to parse auth header JWT: token signature is invalid: crytographic signature invalid",
    "message": "Internal Server Error"
}
```

while trying to reach `app.bsky.feed.generator/whats-hot`. Other accounts on the same server can access discovery normally.

Any ideas how to fix this?

**Comment by stephankaag** [comment]
@MilanBabuljak Was it indeed solved after 24H? I'm running into the same error.

**Comment by MilanBabuljak** [comment]
Yep, can confirm that after all of migrated accounts started working (the most it took was 36h)
