### ISSUE TITLE
Session Refresh Not Working

### ISSUE THREAD

**Issue by Monikaya** [bluesky-social/pds#106]
Hi, recently I attempted to migrate my PDS to another server host by copying the /pds directory, since I was not able to find any documentation on this.

Now, I am coming upon the issue where first I login to the app or website, but after a leaving it idle/closing the app, I come back to it with me logged out. I attempted to check the web logs for this, and it seems like the getSession and refreshSession calls are returning with a 400 error code. I'm not sure why this is happening or how to otherwise troubleshoot it so far.

Any help would be appreciated, much thanks.

**Comment by Isolyth** [comment]
Are you using a cloudflare tunnel? If so, make sure you are using v2024.10.1, prior versions were messing up refreshsession

**Comment by Monikaya** [comment]
Oh yes that's me! It was working before so I didn't consider it. I'm just
on a trip but I'll let you know when I try that. Thanks :)

**Comment by Monikaya** [comment]
It works! Thank you :)
