### ISSUE TITLE
Deleting a user doesn't delete user completly from database

### ISSUE THREAD

**Issue by michelleDeko** [bluesky-social/pds#11]
Hello,

I was having issues with creating a new user, after deleting an old one with the same username / e-mail. After some troubleshooting I found out that, after deleting a user, the user gets removed from "user_account" but doesn't get deleted from "user_pref".
After deleting the user from "user_pref" I could use my @ again.

**Comment by Jacob2161** [comment]
A new update is coming with support for the production network and a `pdsadmin` helper CLI, please let us know if there are any issues after this has been pushed. Thank you!
