### ISSUE TITLE
404 for `list` and `reset-password` on functional PDS

### ISSUE THREAD

**Issue by Zetaphor** [bluesky-social/pds#111]
I've installed the latest PDS on a new VPS and everything appears to be functional. I was able to migrate two accounts without any issue.

However whenever I try and run any of the `pdsadmin` commands I get a 404:

```bash
root@bsky-pds:/home/zetaphor# pdsadmin list
curl: (22) The requested URL returned error: 404
ERROR: list not found
root@bsky-pds:~$ pdsadmin reset-password did:plc:wr6frczaoowsvwpzfkch4vi3
curl: (22) The requested URL returned error: 404
ERROR: reset-password not found
```

I have verified the health endpoint is working correctly:

https://pds.zetaphor.com/xrpc/_health

**Comment by edavis** [comment]
@Zetaphor list and reset-password are sub-commands of `pdsadmin account` so it should be:

```bash
# pdsadmin account list
# pdsadmin account reset-password
```

**Comment by Zetaphor** [comment]
Yep, the indentation threw me off. Thanks!
