### ISSUE TITLE
goat: error when migrating preferences

### ISSUE THREAD

**Issue by mikewmerritt** [bluesky-social/pds#112]
I tried to run goat to migrate my account (mikewmerritt.com), and this error came up when migrating preferences:

> error: failed importing preferences: json: error calling MarshalJSON for type bsky.ActorDefs_Preferences_Elem: cannot marshal empty enum

Digging deeper, it appears the issue is on the export side. I ran `goat bsky prefs export > prefs.json` manually and got much the same error:

> error: json: error calling MarshalJSON for type bsky.ActorDefs_Preferences_Elem: cannot marshal empty enum

I then tried using goat to migrate newly created bsky.social account with no edits to preferences and faced no issues.

**Comment by bnewbold** [comment]
I think this is due to lexicons being out of sync. The preferences endpoints are probably ones that should bypass marshalling and just pass raw JSOn around.

**Comment by benharri** [comment]
i ran into this as well, my workaround was to get the prefs json (copy as curl from devtools), edit by hand and re-import

thread with more info:
https://bsky.app/profile/benharr.is/post/3l7qbwn6h422p

**Comment by mikewmerritt** [comment]
Looks like this is fixed. I was able to migrate successfully (other than my app passwords).
