### ISSUE TITLE
"Not a supported handle domain."

### ISSUE THREAD

**Issue by femtoAmpere** [bluesky-social/pds#12]
Hello!
I hope all is well.

I've set up a pds on https://bsky.femtoAmpere.art/:
```bash
$curl https://bsky.femtoAmpere.art/xrpc/_health 
{"version":"0.2.0-beta.5"}
```

However, if I want to create an account in the sandbox using my invite code I get the following on https://bsky.app/:
![image](https://github.com/bluesky-social/pds/assets/3886111/bbc4023b-58ea-41de-99e7-3453f1102dfe)

Is this expected behaviour and I'm missing something big here? Is this an issue of https://bsky.app/? I am,
- using nginx reverse proxy instead of caddy.
- on a Debian Buster VPS:
```bash
$lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

Thank yoou~

**Comment by femtoAmpere** [comment]
...after typing this out, I am aware that there is
https://bsky.app/
-and-
https://app.bsky-sandbox.dev/

However, I have the same issue there:
![image](https://github.com/bluesky-social/pds/assets/3886111/2d5f5603-fc25-46ef-b00f-7be6d809273a)

**Comment by bnewbold** [comment]
From https://bsky.femtoampere.art/xrpc/com.atproto.server.describeServer, I can see that you do have `availableUserDomains` configured.

I'm not very confident about this, but could you try re-configuring and signing up with the domain entirely lower-case? We consider handles to be case-insensitive but normalized to all lower-case. There might be some code path doing partial normalization resulting in this error.

**Comment by femtoAmpere** [comment]
Thank you for the update! Yes, this did the trick; I could successfully create my account. Should this issue go close or rather keep it open until the `readme.md` is updated?

FYI I'm now at the point where my account does not exist, but I also don't know what to expect in the sandbox network.
![image](https://github.com/bluesky-social/pds/assets/3886111/4067b2c7-505e-40e1-a3f2-c2adf4ace6b4)

**Comment by danieljonce** [comment]
@femtoAmpere, I had a similar "Page not found" issue, but it was because at the time I installed PDS and logged in the first time, my wildcard subdomains `*.mypds.example.com` weren't accessible. After making sure both the `mypds.example.com` and `*.mypds.example.com` were accessable via SSL I re-installed with the `installer.sh` and created an account and the "Page not found" message went away and I see my account page as expected.

**Comment by Jacob2161** [comment]
A new update is coming with support for the production network and a `pdsadmin` helper CLI, please let us know if there are any issues after this has been pushed. Thank you!
