### ISSUE TITLE
Pdsadmin script URL returns 404 not found

### ISSUE THREAD

**Issue by aaplmike** [bluesky-social/pds#144]
In the code it specifies: https://raw.githubusercontent.com/bluesky-social/pds/main/pdsadmin

However, that URL gives a 404. Is there an updated location for the pdsadmin script?

**Comment by kaptenkrille** [comment]
I had same issue when i tried 'pdsadmin list' but then I saw that correct syntax was 'pdsadmin account list' and that worked.

**Comment by aaplmike** [comment]
Thanks. There are several scripts that are installed locally as part of the base install, apparently, list being one of them, and it works.
However, if you look at the script you’ll see there is a URL where the scripts are downloaded from. 
This URL is giving a 404, so scripts like reset-password, which aren't initially downloaded locally, are not working.
