### ISSUE TITLE
OpenSSL: error:0A000438:SSL routines::tlsv1 alert internal error

### ISSUE THREAD

**Issue by danieljonce** [bluesky-social/pds#15]
After fresh installs of both Ubuntu 22.04 and Debian 12 and then running the install.sh script I'm getting internal SSL errors when trying to verify the health of PDS.

***

In Debian:

When I run:
`curl https://[domain_redacted]/xrpc/_health`
I'll get a 502 Error from Cloudflare reporting a SSL misconfiguration

If I go directly to the local IP address:
`curl https://[ipaddress_redacted]/xrpc/_health`
I get
`OpenSSL/3.0.9: error:0A000438:SSL routines::tlsv1 alert internal error`

***

In Ubuntu using `wget` or `curl` I have a similar experience. Example of the `wget` OpenSSL error:

```
--2023-09-22 00:19:44--  https://[ipaddress_redacted]/xrpc/_health
Connecting to [ipaddress_redacted]:443... connected.
OpenSSL: error:0A000438:SSL routines::tlsv1 alert internal error
Unable to establish SSL connection.
```

***

I'm running a reverse proxy, and when I point the domain to a different service on my network to make sure my DNS is configured properly, it works as expected.

This is my pds.env:

```
PDS_HOSTNAME=pds.[redacted].dev
PDS_JWT_SECRET=[redacted]
PDS_ADMIN_PASSWORD=[redacted]
PDS_REPO_SIGNING_KEY_K256_PRIVATE_KEY_HEX=[redacted]
PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX=[redacted]
PDS_DB_SQLITE_LOCATION=/pds/pds.sqlite
PDS_BLOBSTORE_DISK_LOCATION=/pds/blocks
PDS_DID_PLC_URL=https://plc.bsky-sandbox.dev
PDS_BSKY_APP_VIEW_ENDPOINT=https://api.bsky-sandbox.dev
PDS_BSKY_APP_VIEW_DID=did:web:api.bsky-sandbox.dev
PDS_CRAWLERS=https://bgs.bsky-sandbox.dev
```

This is my Caddyfile:
```
{
        email [redacted]@gmail.com
        on_demand_tls {
                ask http://localhost:3000
        }
}

*.pds.[domain_redacted].dev, pds.[domain_redacted].dev {
        tls {
                on_demand
        }
        reverse_proxy http://localhost:3000
}
```

I just found PDS today so I expect I'm missing something obvious in my configuration.

Has anyone else run into this?

**Comment by Jacob2161** [comment]
If you have Cloudflare in front of your PDS, that may not work out of the box, I'd expect it to not work since Caddy is expecting to be able to create a TLS certificate through ZeroSSL/Let's Encrypt.

You can check the caddy logs with `sudo docker logs caddy` to see if there's anything helpful in there.

**Comment by danieljonce** [comment]
Hmm, I tried both proxied and "DNS only" in Cloudflare, but that's helpful info. I'll poke around a bit more.

Thank you for the reply, I'll check the docker logs for caddy as you suggested.

**Comment by danieljonce** [comment]
I resolved my issue by pointing my reverse proxy (Nginx Proxy Manager) to my pds server port 3000 instead of 443.

**Comment by AndreiSva** [comment]
Dealing with the same problem, also using cloudflare but with DNS only enabled.

**Comment by AndreiSva** [comment]
Ah, turns out I had another process using port 3000. It's all good now

**Comment by strongbugman** [comment]
Hate services with SSL included by default, let user config their SSL themselves pls.
