### ISSUE TITLE
"jwt expired" Error when attempting to move PDS to another machine

### ISSUE THREAD

**Issue by hugeblank** [bluesky-social/pds#153]
I set my PDS up temporarily on my PC, with the intent of reconfiguring the network ahead of it to point to a server that it would run on. I finally got around to that, and moved the PDS. Everything seems to work fine, like I can log into it through other apps (pdsls), but bsky.app refuses to work, emitting "jwt expired" when I log in and go to my profile. This is also confirmed by the majority of responses coming from my server returning an error 401 in the network tab. 

To reproduce the issue:
1. Set up an instance on machine A, and create an account.
2. Shut down the instance, and sftp into machine B from machine A. 
3. Copy all the files from A to B. 
4. Reconfigure the network ahead of the machines to point the domain that was pointing at machine A to now point at machine B. 
5. Launch the instance on machine B
6. Log out and log back in on bsky.app. Going to the profile tab should show "jwt expired" after a bit, along with a slew of 401 errors.

**Comment by pfaffman** [comment]
I've been wondering how hard it was to move to a new server.

Can you confirm that your new server is indeed responding as expected on the same URL as before?

Does https://YOURHOST/xrpc/_health give the version? Does https://YOURHOST give you the "This is an AT Protocol Personal Data Server (PDS): https://github.com/bluesky-social/atproto" message?

**Comment by hugeblank** [comment]
Everything looks completely normal, feel free to see for yourself. It's hosted at `pds.atproto.hugeblank.dev`

**Comment by pfaffman** [comment]
I was afraid of that.

It could still be DNS lag, though. When I move Discourse sites to a new server, it often takes a browser that's connected to the old server to be convinced that it needs to drop the connection, get a new IP, and try again.

Oh,  but maybe it's YOUR browser. Have you tried an incognito window? I just tried to create a handle on your domain and it correctly said that the invite code was bogus.

**Comment by hugeblank** [comment]
It's not DNS, it's been pointing to the right place properly for hours now, and it's not cache, I've cleared it for bsky.app and it still does not work

**Comment by hugeblank** [comment]
I'll be keeping an eye on the atproto issue and close this one when that one is closed.

**Comment by hugeblank** [comment]
Issue resolved, see attached issue on atproto (3081) for solution. The fix is very funny.
