### ISSUE TITLE
"Page not found" on Profile page until handle change

### ISSUE THREAD

**Issue by danieljonce** [bluesky-social/pds#17]
With a fresh install of pds version 0.3.0-beta.3 on Ubuntu 22.04 using the installer script, after creating a new account, the Profile page shows "Page not found" but if I go to "settings" and change my handle, it starts working.

**Comment by YOCKOW** [comment]
As described in https://github.com/bluesky-social/pds/issues/12#issuecomment-1731590917 ,
"Page not found" is viewed even after changing the handle...

**Comment by Jacob2161** [comment]
A new update is coming with support for the production network and a `pdsadmin` helper CLI, please let us know if there are any issues after this has been pushed. Thank you!
