### ISSUE TITLE
List of Env Variables for pds.env

### ISSUE THREAD

**Issue by yashasjindal** [bluesky-social/pds#173]
I was reading this old issue #57 which mentioned that the README used to have a list of env vars at the end, but I can't find it.

I was trying to make my self hosted PDS open sign up rather than relying on an invite code, so I tried adding `PDS_INVITE_REQUIRED=false` to my /pds/pds.env file and restarted the PDS after reading about it somewhere online (might have been an outdated var because of the active development on the project/protocol).

Anyways, I was wondering if there's an aggregated list of all the available environment variables which can be referenced by the community (especially to make their PDSes open sign up?)

**Comment by gravityfargo** [comment]
See the atproto [env.ts](https://github.com/bluesky-social/atproto/blob/c72145dbeb2d67068bc28c00a13447e0d382d121/packages/pds/src/config/env.ts#L94)

**Comment by yashasjindal** [comment]
I see, it makes sense. I just want to clarify that any of the variables named `envInt`, `envStr`, `envBool` or `envList` can be be defined in the `/pds/pds.env` file, and it will be picked up from there right?

**Comment by gravityfargo** [comment]
That is correct. For instance 
```ts
port: envInt('PDS_PORT')
``` 
can be used in docker-compose as

```yaml
environment:
  - PDS_PORT=3001
```

I only use a couple, so mileage may vary as to their purpose, or how they're interpreted when passed from a PDS instance.

**Comment by yashasjindal** [comment]
That makes sense, though I was under the impression if I change anything directly in the `docker-compose.yaml`, the changes would be reverted to default on the next `pdsadmin update`, but the variables defined in `pds.env` would persist across versions?

**Comment by gravityfargo** [comment]
I'm not sure. I don't use the stock installation method.

**Comment by yashasjindal** [comment]
I see, thanks for the help! :)

**Comment by bnewbold** [comment]
just to follow up here: don't disable invite codes (`PDS_INVITE_REQUIRED`) unless you know what you are doing and have strong mitigations for spam accounts. there are instructions in the README for generating and sharing invite codes.

**Comment by yashasjindal** [comment]
> just to follow up here: don't disable invite codes (`PDS_INVITE_REQUIRED`) unless you know what you are doing and have strong mitigations for spam accounts. there are instructions in the README for generating and sharing invite codes.

Thanks for following up, that makes sense. I was messing around with making a public PDS for my university at the time. I have reworked it to use invite codes now.
