### ISSUE TITLE
Account creation failed

### ISSUE THREAD

**Issue by forza7taka** [bluesky-social/pds#19]
When I start sandbox pds and create an account, the following log is output and account creation fails.
PDS is running with the DB relationship cleared.
-------------------------------------------------------------------------------------------------------------------
Sep 30 23:15:52 i-50100000502679 node[260644]: {"level":50,"time":1696083352922,"pid":260644,"hostname":"i-50100000502679","name":"pds","req":{"id":4,"method":"POST","url":"/xrpc/com.atproto.server.createAccount","query":{},"params":{},"headers":{"host":"n.redocean.one","x-real-ip":"14.12.120.32","x-forwarded-for":"14.12.120.32","connection":"close","content-length":"120","content-type":"application/json","accept-encoding":"gzip","user-agent":"okhttp/4.9.2"}},"didKey":"did:key:zQ3shnKSeGZp3Kc1KPTYn55bKpdjw7cpvaZzyZErNqcW7i4EE","handle":"forza7.n.redocean.one","msg":"failed to create did:plc"}
Sep 30 23:15:55 i-50100000502679 node[260644]: {"level":50,"time":1696083352927,"pid":260644,"hostname":"i-50100000502679","name":"xrpc-server","err":{"type":"PlcClientError","message":"Request failed with status code 400","stack":"Error: Request failed with status code 400\n    at Function.fromAxiosError (/home/sandbox-pds/node_modules/node_modules/.pnpm/@did-plc+lib@0.0.1/node_modules/@did-plc/lib/src/client.ts:160:12)\n    at Client3.sendOperation (/home/sandbox-pds/node_modules/node_modules/.pnpm/@did-plc+lib@0.0.1/node_modules/@did-plc/lib/src/client.ts:66:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at <anonymous> (/home/sandbox-pds/node_modules/@atproto/pds/src/api/com/atproto/server/createAccount.ts:78:13)\n    at <anonymous> (/home/sandbox-pds/node_modules/@atproto/pds/src/db/index.ts:180:23)\n    at <anonymous> (/home/sandbox-pds/node_modules/node_modules/.pnpm/kysely@0.22.0/node_modules/kysely/dist/esm/kysely.js:370:32)\n    at DefaultConnectionProvider.provideConnection (/home/sandbox-pds/node_modules/node_modules/.pnpm/kysely@0.22.0/node_modules/kysely/dist/esm/driver/default-connection-provider.js:10:20)\n    at Database.transaction (/home/sandbox-pds/node_modules/@atproto/pds/src/db/index.ts:175:30)\n    at handler (/home/sandbox-pds/node_modules/@atproto/pds/src/api/com/atproto/server/createAccount.ts:49:22)\n    at <anonymous> (/home/sandbox-pds/node_modules/@atproto/xrpc-server/src/server.ts:254:35)","status":400,"data":{"type":"Object","message":"Operations not correctly ordered","stack":""}},"msg":"unhandled exception in xrpc method com.atproto.server.createAccount"}

**Comment by Jacob2161** [comment]
A new update is coming with support for the production network and a `pdsadmin` helper CLI, please let us know if there are any issues after this has been pushed. Thank you!
