### ISSUE TITLE
Please provide documentation for running the web interface

### ISSUE THREAD

**Issue by girlpunk** [bluesky-social/pds#21]
As per title, please provide documentation for running the web interface in conjunction with the data server

Thanks

**Comment by T0biii** [comment]
The Repo for the Webinterface is here: https://github.com/bluesky-social/social-app
they push an image ghcr:
https://github.com/bluesky-social/social-app/blob/main/.github/workflows/build-and-push-bskyweb-ghcr.yaml
(  "image.name": "ghcr.io/bluesky-social/social-app:bskyweb-8e9cf182c2e247203b6b5ea9ae701c039945d6a0")
but unfortunately I couldn't find it

there is a Dockerfile so i can build the image myself try something like this:
```bash
git clone https://github.com/bluesky-social/social-app
cd social-app
docker build --tag "social-app:bskyweb-1.53.0" #-maybe change the Version
docker run -d -p 8100:8100 "social-app:bskyweb-1.53.0" bskyweb serve
```
then it is running under port ":8100"
