### ISSUE TITLE
DNS TXT Record for Domain Handle

### ISSUE THREAD

**Issue by kalross** [bluesky-social/pds#24]
Have self  hosted a PDS for testing and when trying to validate DNS TXT record to change handle to domain, the client just pulls the first and oldest TXT record and fails verification.     

dig TXT _atproto.domain.foo pulls the expected TXT record, so don't know why verification isn't working.

Is the TXT record cached somewhere and if so, how do I reset it pds side? 

Thanks.

**Comment by Jacob2161** [comment]
A new update is coming with support for the production network and a `pdsadmin` helper CLI, please let us know if there are any issues after this has been pushed. Thank you!
