### ISSUE TITLE
Invalid Handle when creating new users to a recently created PDS

### ISSUE THREAD

**Issue by aalonsolopez** [bluesky-social/pds#25]
![imagen](https://github.com/bluesky-social/pds/assets/49404378/17ee5e2b-fa71-4d73-abaf-42a8cb5a62be)

This is an example of the result when creating a new user to the PDS. I have some doubts about what is causing this or if we have to wait a bit to get rid of it.

**Comment by aalonsolopez** [comment]
I have to add that I've changed it a couple of  times and the error still there

**Comment by aalonsolopez** [comment]
No news yet 
     
     
      
     
    
    
     
       
      
     
    
    
    
     
     
       On martes, oct 24, 2023 at 7:09 p. m., Maxence Rose ***@***.***> wrote: 
       
      
      
       
      Do you have any news about this bug? I am facing the same problem. 
      —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***> 
      ***@***.***": ***@***.***": "EmailMessage","potentialAction": ***@***.***": "ViewAction","target": "https://github.com/bluesky-social/pds/issues/25#issuecomment-1777670416","url": "https://github.com/bluesky-social/pds/issues/25#issuecomment-1777670416","name": "View Issue"},"description": "View this Issue on GitHub","publisher": ***@***.***": "Organization","name": "GitHub","url": "https://github.com"}}]

**Comment by pirmax** [comment]
Nothing has changed on their side for a few days, it's painful, the project is not moving forward.

**Comment by bnewbold** [comment]
Can you share more context about this? How are you running the PDS, which version/deployment of the bsky web application are you using, are you using individual custom domains as handles or subdomains, do you have wildcard DNS set up, etc.

**Comment by pirmax** [comment]
Hey @bnewbold,

I use a username with the domain of my PDS instance (pirmax.rebroad.com).

I created my account via the bsky.app interface, and when I log in, the interface does not know my information.

Rebroad PDS seems to works : https://rebroad.com/xrpc/_health
My profile exists too : https://pirmax.rebroad.com/.well-known/atproto-did

Thanks.

**Comment by roboli** [comment]
Same issue here :(

**Comment by roboli** [comment]
I added a second account. When I login, I see "invalid.handle" for the account I'm signed in but I see the correct handle for the other account in Settings. If I switch accounts, the same happens but the other way around. Hope it makes sense.

**Comment by roboli** [comment]
Turns out that updating handle for my profile wasn't complicated (even silly not figuring it out sooner), just need to change handle in my Settings, more [here](https://atproto.com/blog/rate-limits-pds-v3#handle-invalidations-on-app-view). Interesting enough, you can send a POST to your PDS to do that too:

https://mydomain.xyz/xrpc/com.atproto.identity.updateHandle

with something like `{
  "handle": "newhandle.mydomain.xyz"
}`

**Comment by Jacob2161** [comment]
A new update is coming with support for the production network and a `pdsadmin` helper CLI, please let us know if there are any issues after this has been pushed. Thank you!

**Comment by astrojuanlu** [comment]
Note that, if you want to host a PDS just for yourself, you don't need the wildcard DNS record, just the one corresponding to the account you're creating.

For example, I am hosting the pds service on `bsky.juanlu.space`, and created an account at `astrojuanlu.bsky.juanlu.space`. Initially I had this "invalid handle" error, until I realized that the `A` record for the subdomain wasn't there.
