### ISSUE TITLE
Cant Search BSky Users on PDS

### ISSUE THREAD

**Issue by rpiadam** [bluesky-social/pds#28]
is their way we can search follow bsky users on our own pds?

Having issues cant see bsky users and @hockley.info on my pds and profile shows as blank like not their 

end point showing PDS_BSKY_APP_VIEW_ENDPOINT=https://api.bsky-sandbox.dev

**Comment by Jacob2161** [comment]
A new update is coming with support for the production network and a `pdsadmin` helper CLI, please let us know if there are any issues after this has been pushed. Thank you!
