### ISSUE TITLE
Kubernetes deployment

### ISSUE THREAD

**Issue by temujin9** [bluesky-social/pds#3]
This happens to be a specialty of mine, and in my experience offers several advantages over Docker Compose setups. Would you be open to a PR to add the option?

**Comment by Jacob2161** [comment]
Thanks for the question. We definitely don't have plans to replace the standalone compose method because of its simplicity.

Maybe we can see if there's demand for running the PDS on Kubernetes and consider adding instructions/configs here?

You're obviously completely free to create your own repo that gives instructions/configs for Kubernetes and it could get linked to from various places.

**Comment by benwsapp** [comment]
@temujin9 looks right now porting the "installer.sh" over to be a Kubernetes deployment wouldn't take much time/effort. env vars for a few necessary tokens and to point to the sandbox endpoints for DID, app view, and crawlers. then add sqlite and an ingress/TLS termination and it's done. there'd surely be value in creating a Helm chart for folks comfortable in Kubernetes to be able to stand up a sandbox PDS that way. I'm happy to collaborate if you want to set up a repo

but @Jacob2161 it _seems_ like the PDS app is deployed by default to ECS and backed by postgres (vs docker compose and sqlite). I'm assuming there's concern about communicating the env vars and config for that type of deployment at this early stage of PDS as a project. but can we expect eventually for there to be a recommended production architecture for PDS? or even to help develop such a thing?

**Comment by benwsapp** [comment]
I later saw at the bottom of the README there's a link to the additional env vars. I still couldn't get postgres to work, but I didn't try very hard. Even when setting all the postgres environment variables, it defaulted to localhost as the address.

I spun up a chart real quick that's _super_ messy for now. It essentially does what the installer script does but much worse:
https://github.com/benwsapp/pds-chart

I'll clean it up over time or I'm happy to work out of someone else's repo/project. But figured I'd get something going just to get started learning deploying the PDS app for now

**Comment by temujin9** [comment]
@benwsapp Fast work! I might take a stab at the postgres part tomorrow.

@Jacob2161 It feels like the best place for this to live would be a subdirectory here, so that it can iterate with the base deployables. I'm not 100% sure Helm allows that (it's a bit since I've used it), but assuming it can be done would y'all be comfortable with that as a destination?

**Comment by benwsapp** [comment]
> @benwsapp Fast work! I might take a stab at the postgres part tomorrow.

only issue with postgres was i didn't prefix the connection string with `postgresql://` 😅

**Comment by Jacob2161** [comment]
The expectation here is that this PDS repo is for single server instances so it probably doesn't make sense for a K8S deployment. Even our own PDS deployments will likely be single server in many cases, with well-tested backup/restore automation.
