### ISSUE TITLE
Multi-protocol routing options

### ISSUE THREAD

**Issue by HelloFillip** [bluesky-social/pds#30]
I currently have several data solutions operating at the root of my domain, including ActivityStreams / ActivityPub, Solid, and now ATP. The goal is to enable a reverse proxy to route to the appropriate service based on the request content (essentially URL pattern and headers). 

Are there recommended methods of defining this separation to route requests to the PDS appropriately?

**Comment by bnewbold** [comment]
Currently, almost all atproto routes have the prefix `/xrpc/`, and it should be pretty easy to configure nginx (or other web servers) to route just those requests to a PDS implementation.

It is conceivable that this prefix could change in the future; we don't use the term "XRPC" much any more, as it is a bit confusing. In short we aren't promising that this routing will work forever. But it should work for now.

**Comment by Jacob2161** [comment]
The `/xrpc/` prefix is very unlikely to ever change, so should be safe to forward explicitly.
