### ISSUE TITLE
Docker update error pds

### ISSUE THREAD

**Issue by T0biii** [bluesky-social/pds#35]
the "containrrr/watchtower" gives me the following error:
```
Could not do a head request for "ghcr.io/bluesky-social/pds:latest", falling back to regular pull.
Reason: registry responded to head request with "404 Not Found", auth: "not present"
Unable to update container "/pds": Error response from daemon: manifest unknown. Proceeding to next.
```

if i try:
`docker compose pull`
i get this error:
`Error response from daemon: manifest unknown`

**Comment by TimBurga** [comment]
Error is still occurring as of 6pm CST last night (Feb 18 2024)

**Comment by Jacob2161** [comment]
A new update is coming with support for the production network and a `pdsadmin` helper CLI, please let us know if there are any issues after this has been pushed. Thank you!
