### ISSUE TITLE
Email verification functionality

### ISSUE THREAD

**Issue by sirodoht** [bluesky-social/pds#44]
I have deployed an instance of my own PDS. I am using bsky.app as a client. On settings there is a `Verify My Email` button, which I click but no email is received. Am I supposed to set up SMTP on the PDS or is the client's job?

Thanks!

**Comment by devinivy** [comment]
Emails are sent from the PDS itself, so it does require a bit fo configuration to get working.  You can configure an SMTP server for sending email from your PDS to the accounts hosted on it:
```sh
PDS_EMAIL_SMTP_URL=smtp://...
PDS_EMAIL_FROM_ADDRESS=admin@...
```

If you don't have an SMTP server lying around, you could catch all outgoing emails by configuring it to point at something like Ethereal: https://ethereal.email/.  Personal email providers sometimes also offer credentials for sending email via SMTP, e.g. gmail has some details for its support here: https://support.google.com/a/answer/176600?hl=en

**Comment by sirodoht** [comment]
Great, thanks both!

**Comment by hyperreal64** [comment]
> I would recommend resend.com if you don't have a SMTP server.

Hey, I'm using resend.com and I still can't seem to get the email verification to work. I have `PDS_EMAIL_SMTP_URL=smtp://resend:<APIKEY>@smtp.resend.com:465/` defined in `/pds/pds.env`, but I get the following internal error:

```
Error: Connection timeout\n    at SMTPConnection._formatError (/app/node_modules/.pnpm/nodemailer@6.9.9/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)\n    at SMTPConnection._onError (/app/node_modules/.pnpm/nodemailer@6.9.9/node_modules/nodemailer/lib/smtp-connection/index.js:776:20)\n    at Timeout.<anonymous> (/app/node_modules/.pnpm/nodemailer@6.9.9/node_modules/nodemailer/lib/smtp-connection/index.js:235:22)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)
```

The formatError bit seems to suggest it's an issue with the way the values in the `PDS_EMAIL_SMTP_URL` are structured. I've tried various inputs, to no avail.

**Comment by hyperreal64** [comment]
> Use port 587 instead of 465

I've tried that. That's the default when you don't specify the port number.

**Comment by rafaeleyng** [comment]
See https://github.com/bluesky-social/pds/pull/86
