### ISSUE TITLE
Profile not found

### ISSUE THREAD

**Issue by turbulent-network** [bluesky-social/pds#56]
Hello,

After a PDS reinstall (with a new handle, new subdomain, etc), it seems the profile isn't found, despite being able to validate the email address (got the confirmation code, etc).

No "handle error" issue, everything seems fine, I can access other peoples' feed etc, but can't:

* view my own profile
* post
* follow other users

I'm not sure how to debug this.

Regards,

**Comment by OliverPifferi** [comment]
> After a PDS reinstall (with a new handle, new subdomain, etc), it seems the profile isn't found, despite being able to validate the email address (got the confirmation code, etc).

Same issue here - clean install, login was possible without any problems - the other problems exactly match by 100% with your ones. Would also be interested to know how to solve this.

**Comment by OliverPifferi** [comment]
@turbulent-network Found out that it started working after getting the information that the server had been federated on Discord. Maybe this solves your issue, too?

**Comment by OliverPifferi** [comment]
Had exactly the same issue - feeds were okay but no following of single accounts nor viewing/editing the profile on a freshly-created PDS.

Reached out on Discord, opened a ticket and shortly after the "You've been federated"-message appeared, the profile worked as the ones from the "official" instance. Doesn't have to mean anything but seems to be more than simple coincidence 😉 !

**Comment by OliverPifferi** [comment]
Yeah, that's the process at the moment but won't be necessary in the future as the README of the repo tells. Good luck! 👍🏻
