### ISSUE TITLE
Domain Issue

### ISSUE THREAD

**Issue by rpiadam** [bluesky-social/pds#59]
Subdomains work but main domain dont work PDS please fix this bug Invailed Handle @Libertywave.app Cant Resolve Host issue keeps happing been on going for ages subdomain works only PDs

**Comment by erlend-sh** [comment]
There seems to still be some unclarity about this:

https://bsky.app/profile/just.anna.lgbt/post/3l6smgz3lbs23
https://bsky.app/profile/tenrys.bsky.social/post/3l6ssomyfgd2v
