### ISSUE TITLE
"User Not Found" and "Actor Not Found" after creating a sandbox PDS and creating a user

### ISSUE THREAD

**Issue by ThatLinuxNerd** [bluesky-social/pds#6]
Following creating a PDS using automated install and inviting a user to test it out it you can't actually view the user's profile, or do any actions as said user. I am extremely inexperienced when it comes to Bluesky and the AT protocol, so if I'm missing something obvious please don't hesitate to say. Here are the log messages: 
`Error: Actor not found: linuxuser.[domain name]`
`Error: Error: Params must have the property "actor"`
`Error: Profile not found`

I also noticed that my domain isn't listed in https://atscan.net/pds, if that is important.

**Comment by andylee830914** [comment]
same here

**Comment by michelleDeko** [comment]
Yep can confirm, I have the same problem.

**Comment by ThatLinuxNerd** [comment]
EDIT: Seems like it just needed time to update on https://atscan.net/pds (so perhaps that was just my impatience).

Strangely it seems like it does now work for me, as I was just able to post my first comment. I'm going to leave this open for additional users that experience this issue, especially given that I have nothing that could help figure out the problem.

**Comment by michelleDeko** [comment]
> EDIT: Seems like it just needed time to update on https://atscan.net/pds (so perhaps that was just my impatience).
> 
> Strangely it seems like it does now work for me, as I was just able to post my first comment. I'm going to leave this open for additional users that experience this issue, especially given that I have nothing that could help figure out the problem.

Seems like I now also appear on atscan.net, but I still have the problem same problem. Also deleted users just don't get deleted, on atscan you can see that there are 3 accounts on my pds but I deleted all of them and the username is still taken

**Comment by syui** [comment]
I have the same problem.

```sh
sandbox_pds  | {"level":50,"time":1692169860026,"pid":7,"hostname":"pds","name":"xrpc-server","err":{"type":"XRPCError","message":"Profile not found","stack":"Error: Profile not found\n    at ServiceClient.call (/app/node_modules/@atproto/xrpc/src/client.ts:126:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at handler (/app/node_modules/@atproto/pds/src/api/app/bsky/proxied.ts:9:19)\n    at <anonymous> (/app/node_modules/@atproto/xrpc-server/src/server.ts:207:35)","status":400,"error":"InvalidRequest","success":false},"msg":"unhandled exception in xrpc method app.bsky.actor.getProfile"}
```

**Comment by pirmax** [comment]
> How do we us none sandbox demo api

You can't right now.

**Comment by Jacob2161** [comment]
A new update is coming with support for the production network, please let us know if there are any issues after this has been pushed. Thank you!
