### ISSUE TITLE
PDS defined as both Protocol data Service and Personal Data Server

### ISSUE THREAD

**Issue by nealmcb** [bluesky-social/pds#61]
In the Readme here, I see PDS defined as either Protocol data Service or Personal Data Server.
This is very confusing. If there are really two related but different things, they shouldn't share the same acronym. Furthermore, in the rest of the documentation for bluesky, the acronym should be defined when first used, e.g. https://docs.bsky.app/docs/starter-templates/custom-feeds.

Thanks!

**Comment by bnewbold** [comment]
Hi @nealmcb!

PDS stands for "Personal Data Server". I'll update the confusing sentence, which uses the term "AT Protocol" followed by "data service" (but not intended to be a single acronym. We use "AT Protocol", "Authenticated Transfer Protocol", and "atproto" all interchangably.
