### ISSUE TITLE
Email verification not working

### ISSUE THREAD

**Issue by hyperreal64** [bluesky-social/pds#76]
> I would recommend resend.com if you don't have a SMTP server.

Hey, I'm using resend.com and I still can't seem to get the email verification to work. I have `PDS_EMAIL_SMTP_URL=smtp://resend:<APIKEY>@smtp.resend.com:465/` defined in `/pds/pds.env`, but I get the following internal error:

```
Error: Connection timeout\n    at SMTPConnection._formatError (/app/node_modules/.pnpm/nodemailer@6.9.9/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)\n    at SMTPConnection._onError (/app/node_modules/.pnpm/nodemailer@6.9.9/node_modules/nodemailer/lib/smtp-connection/index.js:776:20)\n    at Timeout.<anonymous> (/app/node_modules/.pnpm/nodemailer@6.9.9/node_modules/nodemailer/lib/smtp-connection/index.js:235:22)\n    at listOnTimeout (node:internal/timers:573:17)\n    at process.processTimers (node:internal/timers:514:7)
```

The formatError bit seems to suggest it's an issue with the way the values in the `PDS_EMAIL_SMTP_URL` are structured. I've tried various inputs, to no avail.

_Originally posted by @hyperreal64 in https://github.com/bluesky-social/pds/issues/44#issuecomment-2219093304_

**Comment by devinivy** [comment]
It may be worth trying `smtps://`:
```
smtps://resend:<APIKEY>@smtp.resend.com:465/
```

Another thing to consider is whether your API key needs to be URI-encoded to deal with any special characters in it.

**Comment by hyperreal64** [comment]
Okay so, my VPS where the PDS is running is hosted on Linode, and Linode blocks ports 25, 465, and 587 to prevent spam. Thankfully resend.com allows using port 2465, so I changed it to

`PDS_EMAIL_SMTP_URL=smtps://resend:<APIKEY>@smtp.resend.com:2465/`

and it works!

I'll close the issue. Thanks.

**Comment by rafaeleyng** [comment]
See https://github.com/bluesky-social/pds/pull/86
