### ISSUE TITLE
Error 401 happening today (xrpc-server)

### ISSUE THREAD

**Issue by Fastidious** [bluesky-social/pds#78]
As of yesterday, my hosted PDS was working just fine. Today I can't see anything on the app, and the following shows on logs (masking server name):

```
Aug 18 19:44:04 servername.example.com node[2530]:{"level":50,"time":1724024644210,"pid":2530,"hostname":"servername.example.com","name":"xrpc-server","status":401,"message":"missing jwt lexicon method (\"lxm\"). must match: app.bsky.graph.getList","name":"BadJwtLexiconMethod","msg":"error in xrpc"}
```

What could be happening?

**Comment by devinivy** [comment]
Hey, you're probably bumping into issues related to the changes detailed here: https://github.com/bluesky-social/atproto/pull/2663.  If you're in the PDS Admins discord there's some more info about it there too: https://discord.com/channels/1207024379549061120/1207024647850430464/1270122028544036864

If you use the default auto-updating PDS distribution then it should have taken care of itself.  If you don't then you can force an update manually:
```
# assuming you are using tag 0.4 in your compose file
docker image pull ghcr.io/bluesky-social/pds:0.4
systemctl restart pds
```

**Comment by Fastidious** [comment]
Thanks for the heads up, @devinivy. I run it without docker. The first thing I did was a `git pull`, and restarted the service. It did not work. I believe I might have missed running `pnpm install --production --frozen-lockfile` within the service directory. That might have been it.

Closing as solved. Thanks!
