### ISSUE TITLE
Self-Hosting PDS Email Question

### ISSUE THREAD

**Issue by tylerchilds** [bluesky-social/pds#82]
Excellent work on Bluesky and ATProto-- super cool work-- I've been enjoying poking around with building a client over the weekend after installing the PDS on a digital ocean ubuntu droplet.

One issue-- and I'm not sure where to ask or troubleshoot, so please point me in the right direction-- I'm trying to change my password to make it easier to log in on other devices, but it looks like I need a code, but email does not seem to be going through.

I've also tried to verify email and that does not seem to go through. I'm connecting through https://bsky.app to connect to my https://1998.social pds as tychi: https://bsky.app/profile/tychi.1998.social

Are there docs on troubleshooting system emails?

**Comment by dolciss** [comment]
Have you set PDS_EMAIL_SMTP_URL ?
https://github.com/bluesky-social/pds/issues/44#issuecomment-1960386820

**Comment by tylerchilds** [comment]
@dolciss I had not yet-- I just tried, but still aren't getting emails through.

Currently, I've added the following to my .bashrc and i reboot my PDS to impotently source it :D 

```
export PDS_EMAIL_SMTP_URL=smtp://xxx@yyy:zzz@smtp.ethereal.email:587/
export PDS_EMAIL_FROM_ADDRESS=warlock@1998.social
```

I did try using sendgrid credentials from an account that I have, but those didn't seem to work either-- which is why i tried the ethereal.email recommendation from the other thread.

I echo the variables out, so I know they're set correctly when the PDS starts cold. Any other tips or tricks?

**Comment by dolciss** [comment]
I think `PDS_EMAIL_SMTP_URL` and `PDS_EMAIL_SMTP_URL` should be configured in `/pds/pds.env`.

**Comment by tylerchilds** [comment]
@dolciss Perfect, that worked- email verified and password updated, server is stable :) 

Thank you for your help.

**Comment by rafaeleyng** [comment]
See https://github.com/bluesky-social/pds/pull/86
