### ISSUE TITLE
How do I change the aws s3 endpoint?

### ISSUE THREAD

**Issue by yks118** [bluesky-social/pds#9]
hello.

I am trying to create pds and try various things.

I know how to use the s3 bucket, but I ask because there seems to be no way to change the endpoint.

I'm currently using cloudflare r2, not aws s3.

**Comment by UpcraftLP** [comment]
THis doesn't seem possible currently, as only the bucket name is passed on from the configuration.
https://github.com/bluesky-social/atproto/blob/c8f1d2e102f181161a556863ada12f8e138c887d/packages/pds/src/context.ts#L94

**Comment by Jacob2161** [comment]
Yes, that's right. Ideally it would work with any S3 compatible storage in the future but probably does not at this time.
