### ISSUE TITLE
Blob limits lower than Bluesky PDS

### ISSUE THREAD

**Issue by electricduck** [bluesky-social/pds#90]
While testing migration, I quickly noticed a bunch of `XRPC 413: PayloadTooLarge` errors indicating the blob size limits are not within parity compared to Bluesky's own PDS, and I was unable to upload large videos to my own PDS.

For some more context: https://bsky.app/profile/ducky.ws/post/3l5uvpork2g2m

**Comment by devinivy** [comment]
This can be adjusted through an environmant variable.  We should ensure the distro works well for video by default, but in the meantime folks can set the following:
```env
PDS_BLOB_UPLOAD_LIMIT=52428800
```
