### ISSUE TITLE
SMTP setting quetions

### ISSUE THREAD

**Issue by miyago9267** [bluesky-social/pds#93]
I referred to #44 and #82 and wrote the settings into `/pds/pds.env`. 

The information filled in is
```
PDS_EMAIL_SMTP_URL=smtps://my_postfix_smtp_domain:465/
PDS_EMAIL_FROM_ADDRESS=admin@my_domain
```

As expected, the mapping in the container was also successful. However, after I reopened the container, the function of sending letters still failed. The smtf server itself is definitely able to send letters, and all other functions are normal. I would like to ask whether Missed something

**Comment by Zetaphor** [comment]
Depending on who you're using for SMTP you will need to include a password or app password. Also you may need to use `smtp://` with port 587

Here's my cofiguration with Google's SMTP:

`smtp://<your-username>:<app-password>@smtp.gmail.com:587`

**Comment by miyago9267** [comment]
OMG, I'm sorry I just saw this reply comment now.
Thank you very much, it really solved my problem, my pds can finally connect to my smtp server successfully, thank you very much!
